// test_verifier_negative.cpp — Negative tests for the entropy proof verifier.
//
// Reads a valid v3 proof file, corrupts specific values, re-writes to a
// temporary file, and verifies the verifier rejects it.
//
// Requires a valid proof at /tmp/test_entropy_v3.proof (generated by
// gold_test_zkentropy or test_zkentropy).
//
// Build: g++ -std=c++17 -O2 -I verifier -o test_verifier_negative test/test_verifier_negative.cpp -lm
// Usage: ./test_verifier_negative

#include "verifier_utils.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <fstream>
#include <vector>
#include <functional>

// ── Proof binary format reader/writer ───────────────────────────────────────

static const uint64_t PROOF_MAGIC_V3 = 0x5A4B454E54523033ULL;

struct RawProof {
    uint64_t magic;
    uint32_t version;
    uint64_t entropy_val;
    uint32_t T;
    uint32_t vocab_size;
    double   sigma_eff;
    uint32_t log_scale;
    uint32_t cdf_precision;
    uint32_t log_precision;
    uint32_t cdf_scale;
    struct Poly {
        std::vector<Fr_t> evals;
    };
    std::vector<Poly> polys;
};

static RawProof read_raw_proof(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f.is_open()) throw std::runtime_error("Cannot open: " + path);

    RawProof p;
    p.magic = read_u64(f);
    p.version = read_u32(f);
    p.entropy_val = read_u64(f);
    p.T = read_u32(f);
    p.vocab_size = read_u32(f);
    f.read((char*)&p.sigma_eff, sizeof(double));
    p.log_scale = read_u32(f);
    p.cdf_precision = read_u32(f);
    p.log_precision = read_u32(f);
    p.cdf_scale = read_u32(f);

    uint32_t n = read_u32(f);
    p.polys.resize(n);
    for (uint32_t i = 0; i < n; i++) {
        uint32_t ne = read_u32(f);
        p.polys[i].evals.resize(ne);
        for (uint32_t j = 0; j < ne; j++) {
            p.polys[i].evals[j] = read_fr(f);
        }
    }
    return p;
}

static void write_raw_proof(const RawProof& p, const std::string& path) {
    std::ofstream f(path, std::ios::binary);
    auto w64 = [&](uint64_t v) { f.write((char*)&v, 8); };
    auto w32 = [&](uint32_t v) { f.write((char*)&v, 4); };
    auto wfr = [&](Fr_t v) { f.write((char*)&v, sizeof(Fr_t)); };

    w64(p.magic);
    w32(p.version);
    w64(p.entropy_val);
    w32(p.T);
    w32(p.vocab_size);
    f.write((char*)&p.sigma_eff, sizeof(double));
    w32(p.log_scale);
    w32(p.cdf_precision);
    w32(p.log_precision);
    w32(p.cdf_scale);

    w32((uint32_t)p.polys.size());
    for (const auto& poly : p.polys) {
        w32((uint32_t)poly.evals.size());
        for (const auto& e : poly.evals) wfr(e);
    }
}

// ── Run verifier as subprocess ──────────────────────────────────────────────

static bool verifier_accepts(const std::string& proof_path) {
    std::string cmd = "./verifier/verifier " + proof_path + " 2>/dev/null >/dev/null";
    int rc = system(cmd.c_str());
    return (rc == 0);
}

// ── Test framework ──────────────────────────────────────────────────────────

static int n_pass = 0, n_fail = 0;

static void check(bool cond, const char* msg) {
    if (cond) {
        n_pass++;
        printf("  PASS: %s\n", msg);
    } else {
        n_fail++;
        printf("  FAIL: %s\n", msg);
    }
}

// ── Compute proof layout offsets ────────────────────────────────────────────

struct ProofLayout {
    uint32_t cdf_start;
    uint32_t cdf_total;
    uint32_t link_start;
    uint32_t rowsum_start;
    uint32_t rowsum_rounds;
    uint32_t extract_start;
    uint32_t extract_rounds;
    uint32_t qr_start;
    uint32_t nonneg_q_start;
    uint32_t nonneg_r_start;
    uint32_t nonneg_gap_start;
    uint32_t ce_idx;
    uint32_t log_start;
    uint32_t log_total;
    uint32_t sum_start;
    uint32_t sum_rounds;
    uint32_t total;
};

static uint32_t compute_r_bits(uint32_t vocab_size, uint32_t cdf_scale) {
    uint32_t r_bits = 1;
    uint64_t max_tw = (uint64_t)vocab_size * cdf_scale;
    while ((1ULL << r_bits) <= max_tw) r_bits++;
    return r_bits;
}

static ProofLayout compute_layout(const RawProof& p) {
    ProofLayout L;
    uint32_t T = p.T, V = p.vocab_size, TV = T * V;
    uint32_t q_bits = p.log_precision + 1;
    uint32_t r_bits = compute_r_bits(V, p.cdf_scale);

    uint32_t N_cdf = 1u << p.cdf_precision;
    uint32_t D_cdf = N_cdf * 2;
    while (D_cdf < TV) D_cdf *= 2;
    uint32_t cdf_p1 = ceil_log2(D_cdf / N_cdf);
    uint32_t cdf_p2 = ceil_log2(N_cdf);
    L.cdf_start = 0;
    L.cdf_total = cdf_p1 + cdf_p2 + 5;

    L.link_start = L.cdf_total;
    uint32_t link_total = 4;

    uint32_t rowsum_rounds = ceil_log2(V);
    L.rowsum_start = L.link_start + link_total;
    L.rowsum_rounds = rowsum_rounds;

    uint32_t extract_rounds = ceil_log2(TV);
    L.extract_start = L.rowsum_start + rowsum_rounds + 2;
    L.extract_rounds = extract_rounds;

    uint32_t extract_total = extract_rounds + 2 + 1;
    L.qr_start = L.extract_start + extract_total;

    L.nonneg_q_start = L.qr_start + 3;
    uint32_t nonneg_q = 1 + q_bits;
    L.nonneg_r_start = L.nonneg_q_start + nonneg_q;
    uint32_t nonneg_r = 1 + r_bits;
    L.nonneg_gap_start = L.nonneg_r_start + nonneg_r;
    uint32_t nonneg_gap = 1 + r_bits;
    L.ce_idx = L.nonneg_gap_start + nonneg_gap;

    uint32_t N_log = 1u << p.log_precision;
    uint32_t D_log = N_log * 2;
    while (D_log < T) D_log *= 2;
    uint32_t log_p1 = ceil_log2(D_log / N_log);
    uint32_t log_p2 = ceil_log2(N_log);
    L.log_start = L.ce_idx + 1;
    L.log_total = log_p1 + log_p2 + 5;

    uint32_t T_padded = 1u << ceil_log2(T);
    L.sum_start = L.log_start + L.log_total;
    L.sum_rounds = ceil_log2(T_padded);

    L.total = L.sum_start + L.sum_rounds + 2;
    return L;
}

// ── Tests ───────────────────────────────────────────────────────────────────

int main() {
    const std::string source = "/tmp/test_entropy_v3.proof";
    const std::string corrupt = "/tmp/test_entropy_corrupt.proof";

    printf("=== Verifier negative tests ===\n\n");

    // Load the valid proof
    RawProof base;
    try {
        base = read_raw_proof(source);
    } catch (const std::exception& e) {
        fprintf(stderr, "Cannot load base proof: %s\n"
                "Run gold_test_zkentropy first to generate it.\n", e.what());
        return 1;
    }

    // Sanity: valid proof passes
    write_raw_proof(base, corrupt);
    check(verifier_accepts(corrupt), "unmodified proof passes verifier");

    auto L = compute_layout(base);

    // ── 1. Bad magic number ─────────────────────────────────────────────
    {
        RawProof p = base;
        p.magic = 0xDEADBEEFDEADBEEFULL;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "bad magic rejected");
    }

    // ── 2. Wrong version ────────────────────────────────────────────────
    {
        RawProof p = base;
        p.version = 99;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong version rejected");
    }

    // ── 3. Wrong polynomial count ───────────────────────────────────────
    {
        RawProof p = base;
        p.polys.push_back({{FR_ZERO}});  // extra polynomial
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "extra polynomial rejected");
    }

    // ── 4. Corrupt linking: diffs(u) ────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.link_start].evals[0] = fr_add(p.polys[L.link_start].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted diffs(u) → LINK fails");
    }

    // ── 5. Corrupt linking: vstar(u) ────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.link_start + 2].evals[0] = FR_ZERO;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted vstar(u) → LINK fails");
    }

    // ── 6. Corrupt QR division: r(u) ────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.qr_start + 1].evals[0] = fr_add(p.polys[L.qr_start + 1].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted r(u) → QR_DIV fails");
    }

    // ── 7. Corrupt bit decomposition: q bit plane ───────────────────────
    {
        RawProof p = base;
        // Flip bit 0 of q
        p.polys[L.nonneg_q_start + 1].evals[0] =
            fr_add(p.polys[L.nonneg_q_start + 1].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted q bit → BITDECOMP_q fails");
    }

    // ── 8. Corrupt bit decomposition: r bit plane ───────────────────────
    {
        RawProof p = base;
        p.polys[L.nonneg_r_start + 1].evals[0] =
            fr_add(p.polys[L.nonneg_r_start + 1].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted r bit → BITDECOMP_r fails");
    }

    // ── 9. Corrupt combined error ───────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.ce_idx].evals[0] = FR_ONE;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "nonzero combined_error → BINARY fails");
    }

    // ── 10. Wrong entropy in header ─────────────────────────────────────
    {
        RawProof p = base;
        p.entropy_val += 1;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong entropy_val → ENTROPY_SUM fails");
    }

    // ── 11. Wrong T in header ───────────────────────────────────────────
    {
        RawProof p = base;
        p.T += 1;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong T → structure mismatch");
    }

    // ── 12. Wrong vocab_size in header ──────────────────────────────────
    {
        RawProof p = base;
        p.vocab_size = 64;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong vocab_size → structure mismatch");
    }

    // ── 13. Corrupt gap bit decomposition ───────────────────────────────
    {
        RawProof p = base;
        p.polys[L.nonneg_gap_start + 1].evals[0] =
            fr_add(p.polys[L.nonneg_gap_start + 1].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted gap bit → BITDECOMP_gap fails");
    }

    // ── 14. Corrupt linking: logits(u) ──────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.link_start + 1].evals[0] =
            fr_add(p.polys[L.link_start + 1].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted logits(u) → LINK fails");
    }

    // ── 15. Corrupt linking: ones_V(u) ──────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.link_start + 3].evals[0] =
            fr_add(p.polys[L.link_start + 3].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted ones_V(u) → LINK fails");
    }

    // ── 16. Corrupt QR: q*tw(u) ─────────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.qr_start + 0].evals[0] =
            fr_add(p.polys[L.qr_start + 0].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted q*tw(u) → QR_DIV fails");
    }

    // ── 17. Corrupt QR: wp_scaled(u) ────────────────────────────────────
    {
        RawProof p = base;
        p.polys[L.qr_start + 2].evals[0] =
            fr_add(p.polys[L.qr_start + 2].evals[0], FR_ONE);
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "corrupted wp_scaled(u) → QR_DIV fails");
    }

    // ── 18. Fewer polynomials ───────────────────────────────────────────
    {
        RawProof p = base;
        p.polys.pop_back();
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "missing polynomial rejected");
    }

    // ── 19. Wrong cdf_precision ─────────────────────────────────────────
    {
        RawProof p = base;
        p.cdf_precision = 12;  // different from real value (16)
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong cdf_precision → structure mismatch");
    }

    // ── 20. Wrong log_precision ─────────────────────────────────────────
    {
        RawProof p = base;
        p.log_precision = 12;
        write_raw_proof(p, corrupt);
        check(!verifier_accepts(corrupt), "wrong log_precision → structure mismatch");
    }

    printf("\n%d passed, %d failed\n", n_pass, n_fail);

    // Cleanup
    remove(corrupt.c_str());

    return n_fail > 0 ? 1 : 0;
}
